export const mainNavbar: string;
export const logo: string;
export const text: string;
export const navbarLeft: string;
export const imageTextPair: string;
export const textDiv: string;
export const item: string;
export const navbarRight: string;
export const signupButton: string;
