export const UPDATE_PRACTICE_BLOCK = 'UPDATE_PRACTICE_BLOCK'
export const CLEAR_REDUX_PRACTICE_PROPS = 'CLEAR_REDUX_PRACTICE_PROPS'
export const PRACTICE_COMPLETED = 'PRACTICE_COMPLETED'
export const UPDATE_PRACTICE_NODES = 'UPDATE_PRACTICE_NODES'